name: CI (CMake)
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - if: matrix.os == 'macos-latest'
        name: Install dependencies (macOS)
        run: |
          brew update
          brew install abseil googletest google-benchmark
        shell: bash
      - if: matrix.os == 'ubuntu-latest'
        name: Install dependencies (Ubuntu)
        run: |
          sudo apt update -y
          sudo apt install -y libabsl-dev libgtest-dev libbenchmark-dev
        shell: bash
      - if: matrix.os == 'windows-latest'
        name: Install dependencies (Windows)
        run: |
          vcpkg update
          vcpkg --triplet x64-windows install abseil gtest benchmark
        shell: bash
      - run: .github/cmake.sh
        shell: bash
